version: '2.5'
services:
  auth-app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: auth-app
    container_name: auth-app
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "7575:80"